
image:
  file: .gitpod.Dockerfile

tasks:
  - before: |
      cd ../player-service
  - init: mvn package -DskipTests

ports:
  - port: 8080  # Port for Spring Boot
    onOpen: open-preview

  - port: 5000  # Port for Python Flask API (or other framework)
    onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot