tasks:
  - init: |
      # Install dependencies for Java and Python
      sudo apt-get update
      sudo apt-get install -y openjdk-17-jdk python3-pip
      pip3 install -r player-ml-model/requirements.txt  # Install Python dependencies
  - name: player-service-app
    command: |
      cd player-service
      ./mvnw package -DskipTests
  - name: player-ml-model
    command: |
      cd player-ml-model
      python3 model.py

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot