
image:
  file: .gitpod.Dockerfile

tasks:
  - name: "Install Spring Boot dependencies"
    init: |
      sudo apt-get update
      sudo apt-get install -y maven
    command: mvn clean install  # Builds the Spring Boot app

  - name: "Install Python dependencies"
    init: |
      sudo apt-get update
      sudo apt-get install -y python3-pip
    command: pip3 install -r player_ml_model/requirements.txt  # Installs Python dependencies

  - name: "Run Spring Boot app"
    command: mvn spring-boot:run  # Runs Spring Boot

  - name: "Run Python ML model"
    command: python3 player_ml_model/model.py  # Runs Python model

ports:
  - port: 8080  # Port for Spring Boot
    onOpen: open-preview

  - port: 5000  # Port for Python Flask API (or other framework)
    onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot