version: '3.8'
services:
  player-service-app:
    build: ./player-service
    container_name: player-service-app
    ports:
      - "8080:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx1024m
    command: ./mvnw spring-boot:run

  python-ml-model:
    build: ./player-ml-model
    container_name: player-ml-model
    ports:
      - "5000:5000"
    command: python3 model.py